/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.randelshofer.scorm;

import ch.randelshofer.gui.Fonts;
import ch.randelshofer.util.ResourceBundleUtil;
import java.util.prefs.Preferences;
import javax.swing.SwingConstants;

/**
 * ExportChooserAccessory.
 *
 * @author Werner Randelshofer
 * @version 1.0 2010-02-10 Created.
 */
public class ExportChooserAccessory extends javax.swing.JPanel {

    private final ResourceBundleUtil labels;
    private CourseModel model;
    private Preferences prefs;

    /** Creates new form ExportChooserAccessory */
    public ExportChooserAccessory() {
        labels = ResourceBundleUtil.getLAFBundle("ch.randelshofer.scorm.Labels");
        initComponents();

        copyEverythingInfoLabel.setText("<html>" + Fonts.smallDialogFontTag(
                labels.getString("export.copyEverything.info")));
        copyEverythingInfoLabel.setVerticalTextPosition(SwingConstants.TOP);
        prefs = Preferences.userNodeForPackage(getClass());
        copyEverythingCheckBox.setSelected(prefs.getBoolean("export.copyEverything", false));

    }

    public void setModel(CourseModel newValue) {
        this.model = newValue;

        copyEverythingCheckBox.setSelected(prefs.getBoolean("export.copyEverything", false));

        if (model != null) {
            // copyEverythingCheckBox.setSelected(model.isCopyEverything());
            model.setCopyEverything(copyEverythingCheckBox.isSelected());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        copyEverythingCheckBox = new javax.swing.JCheckBox();
        copyEverythingInfoLabel = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setLayout(new java.awt.GridBagLayout());

        copyEverythingCheckBox.setText(labels.getString("export.copyEverything.text")); // NOI18N
        copyEverythingCheckBox.addActionListener(formListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 0, 0);
        add(copyEverythingCheckBox, gridBagConstraints);

        copyEverythingInfoLabel.setText(labels.getString("export.copyEverything.info")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 46, 8, 0);
        add(copyEverythingInfoLabel, gridBagConstraints);
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == copyEverythingCheckBox) {
                ExportChooserAccessory.this.copyEverythingPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void copyEverythingPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyEverythingPerformed
        if (model != null) {
            model.setCopyEverything(copyEverythingCheckBox.isSelected());
        }
        prefs.putBoolean("export.copyEverything", copyEverythingCheckBox.isSelected());

    }//GEN-LAST:event_copyEverythingPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox copyEverythingCheckBox;
    private javax.swing.JLabel copyEverythingInfoLabel;
    // End of variables declaration//GEN-END:variables
}
